language: php
php:
- 5.6
- 7.0
- 7.1
- hhvm
install:
  - composer install
script: find {src,tests} -name "*.php" ! -path '*/NonPHP7.php' -print0 \
  | xargs -0 -n1 -P8 php -l \
  | grep -v '^No syntax errors detected' \
  ; test $? -eq 1
